pins.digitalWritePin(DigitalPin.P2, 0)
pins.digitalWritePin(DigitalPin.P2, 1)
pins.digitalWritePin(DigitalPin.P16, 1)
pins.spiPins(DigitalPin.P15, DigitalPin.P14, DigitalPin.P13)
pins.spiFormat(8, 0)
pins.spiFrequency(1000000)
basic.pause(10)
pins.digitalWritePin(DigitalPin.P16, 0)
let cmd = pins.spiWrite(65)
cmd = pins.spiWrite(0)
pins.digitalWritePin(DigitalPin.P16, 1)
cmd = pins.spiWrite(0)
